[package]
name = "my-gdnative-lib"
version = "0.1.0"
authors = ["dru <dru@gamebreakingstudios.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdnative = "0.10"
rand = "0.8"
